import json

# Genre mapping (updated to include more genres)
genre_mapping = {
    "Rock": [
        "alt rock",
        "punk rock",
        "classic rock",
        "hard rock",
        "indie rock",
        "progressive rock",
        "post-rock",
        "glam metal",
        "alternative rock",
        "soft rock",
        "glam rock",
        "garage rock",
        "folk rock",
        "art rock",
        "southern rock",
        "rock and roll",
        "rockabilly",
        "proto-punk",
        "stoner rock",
        "psychedelic rock",
        "acid rock",
    ],
    "Pop": [
        "pop",
        "dance pop",
        "electropop",
        "synthpop",
        "k-pop",
        "j-pop",
        "indie pop",
        "baroque pop",
        "k-ballad",
        "psychedelic pop",
        "acoustic pop",
        "soft pop",
        "city pop",
        "adult standards",
        "bedroom pop",
        "pop punk",
        "britpop",
        "emo pop",
    ],
    "Hip Hop": [
        "hip hop",
        "rap",
        "trap",
        "gangsta rap",
        "conscious hip hop",
        "underground hip hop",
        "trap latino",
        "uk drill",
        "horrorcore",
        "dark trap",
        "k-rap",
        "punk rap",
        "new york drill",
        "g-funk",
        "east coast hip hop",
        "west coast hip hop",
        "cloud rap",
        "rage rap",
        "gangster rap",
        "meme rap",
        "j-rap",
        "underground hip hop",
        "hardcore hip hop",
        "melodic rap",
        "memphis rap",
        "rap metal",
        "southern hip hop",
        "drill",
    ],
    "Electronic": [
        "electronic",
        "edm",
        "house",
        "techno",
        "trance",
        "dubstep",
        "drum and bass",
        "ambient",
        "electro",
        "synthwave",
        "liquid funk",
        "hardstyle",
        "stutter house",
        "progressive trance",
        "italo dance",
        "eurodance",
        "electronica",
        "hyperpop",
        "dark ambient",
        "future bass",
        "rave",
        "hardcore techno",
        "dance",
    ],
    "R&B": [
        "r&b",
        "soul",
        "neo-soul",
        "contemporary r&b",
        "funk",
        "pinoy r&b",
        "chinese r&b",
        "soul blues",
        "smooth jazz",
        "quiet storm",
        "motown",
        "j-r&b",
    ],
    "Jazz": [
        "jazz",
        "smooth jazz",
        "bebop",
        "fusion",
        "acid jazz",
        "vocal jazz",
        "french jazz",
        "soul jazz",
        "jazz blues",
        "swing music",
        "big band",
    ],
    "Classical": [
        "classical",
        "baroque",
        "romantic",
        "modern classical",
        "chamber music",
        "classical piano",
        "choral",
        "neoclassical",
        "requiem",
    ],
    "Metal": [
        "metal",
        "heavy metal",
        "death metal",
        "black metal",
        "thrash metal",
        "power metal",
        "symphonic metal",
        "nu metal",
        "doom metal",
        "metalcore",
        "pirate metal",
        "folk metal",
        "metal",
    ],
    "Country": [
        "country",
        "folk country",
        "bluegrass",
        "americana",
        "outlaw country",
        "alt country",
        "country rock",
    ],
    "Blues": [
        "blues",
        "delta blues",
        "electric blues",
        "blues rock",
        "soul blues",
        "boogie-woogie",
    ],
    "Reggae": ["reggae", "dancehall", "dub", "roots reggae", "spanish-language reggae"],
    "World": [
        "world music",
        "afrobeat",
        "flamenco",
        "balkan",
        "celtic",
        "indian classical",
        "ghazal",
        "canzone napoletana",
        "qawwali",
        "sufi",
        "champeta",
        "bhangra",
        "gujarati garba",
        "bhajan",
    ],
    "Folk": [
        "folk",
        "indie folk",
        "acoustic folk",
        "singer-songwriter",
        "folk pop",
        "chamber pop",
        "harana",
        "kundiman",
    ],
    "Punk": ["punk", "pop punk", "hardcore punk", "post-punk", "emo", "screamo"],
    "Alternative": [
        "alternative",
        "indie",
        "grunge",
        "shoegaze",
        "new wave",
        "alternative dance",
        "post-hardcore",
        "post-grunge",
        "christian alternative rock",
    ],
    "Soundtrack": [
        "soundtrack",
        "film score",
        "video game music",
        "anime",
        "japanese vgm",
        "musicals",
    ],
    "Gospel": [
        "gospel",
        "christian",
        "worship",
        "ccm",
        "christian rock",
        "christian hip hop",
        "christian pop",
        "pop worship",
    ],
    "Latin": [
        "latin",
        "salsa",
        "reggaeton",
        "bachata",
        "bossa nova",
        "samba",
        "latin hip hop",
        "mexican hip hop",
    ],
    "Children's": ["children's music", "lullabies", "nursery rhymes"],
    "Holiday": ["holiday", "christmas", "halloween"],
    "Other": [],  # For genres that don't fit into the above categories
}

# Language mapping (to categorize songs by language)
language_mapping = {
    "Hindi": ["bollywood", "hindi pop", "hindi hip hop", "desi pop"],
    "Tamil": ["kollywood", "tamil pop", "tamil hip hop"],
    "Spanish": ["reggaeton", "latin", "spanish-language reggae"],
    "Korean": ["k-pop", "k-rap", "k-ballad"],
    "Japanese": ["j-pop", "j-rock", "j-rap"],
    "Chinese": ["c-pop", "mandopop", "chinese r&b"],
    "French": ["french jazz", "variété française"],
    "Other Languages": [],  # For languages not explicitly mapped
}


def save_mappings_to_json():
    """
    Save genre and language mappings to JSON files.
    """
    with open("broad_genres.json", "w") as f:
        json.dump(genre_mapping, f, indent=4)
    with open("language_mapping.json", "w") as f:
        json.dump(language_mapping, f, indent=4)
    print("Genre and language mappings saved to JSON files.")


if __name__ == "__main__":
    save_mappings_to_json()
